### ISSUE TITLE
Entities cause crash

### ISSUE THREAD

**Issue by ANT83z4** [gdavid04/phi#26]
Summoned spirit crashed the world and made it permanently crash 
[crash-2024-03-16_15.50.18-client.txt](https://github.com/gdavid04/phi/files/14623963/crash-2024-03-16_15.50.18-client.txt)

**Comment by ANT83z4** [comment]
So, every thing that summons an entity is crashing the game that means psi wave and transfer both do. Including conjure marker

**Comment by gdavid04** [comment]
> Summoned spirit crashed the world and made it permanently crash [crash-2024-03-16_15.50.18-client.txt](https://github.com/gdavid04/phi/files/14623963/crash-2024-03-16_15.50.18-client.txt)

Could you attach a log as well?

**Comment by ANT83z4** [comment]
first should be from psi wave crash and second transform (i mean chronologically)
[crash-2024-03-18_13.46.08-client.txt](https://github.com/gdavid04/phi/files/14636370/crash-2024-03-18_13.46.08-client.txt)
[crash-2024-03-18_13.45.32-client.txt](https://github.com/gdavid04/phi/files/14636371/crash-2024-03-18_13.45.32-client.txt)

**Comment by gdavid04** [comment]
These are crash reports, could you send the logs as well?

**Comment by ANT83z4** [comment]
[latest.log](https://github.com/gdavid04/phi/files/14636405/latest.log)
should be this (crahs to main menu makes getting these confusing i thought i been sending log outputs wops
)

**Comment by ANT83z4** [comment]
Tested distilation chamber. crashes the game but it takes like 0.5s so i managed to save my testing wolrd
(did i mention the entities are invisible?)
(the log file has 435MB how?? I cant send)
but MPU dont cast free blinks on 0 psi unfortunately.
[crash-2024-03-19_18.08.43-client.txt](https://github.com/gdavid04/phi/files/14654046/crash-2024-03-19_18.08.43-client.txt)
[latest.log](https://github.com/gdavid04/phi/files/14654047/latest.log)
(somehow this time its 1000x smaller size)

**Comment by gdavid04** [comment]
Does the issue also occur with all other mods disabled?

**Comment by ANT83z4** [comment]
unless its caused by psionic utilities than yes the issues seem to all remain consitent no texture and distilation crashes after 2s
should i test other things too? tested conjure marker and chamber only here
[2024-03-20-5.log.gz](https://github.com/gdavid04/phi/files/14665702/2024-03-20-5.log.gz)
[2024-03-20-6.log.gz](https://github.com/gdavid04/phi/files/14665703/2024-03-20-6.log.gz)
[latest.log](https://github.com/gdavid04/phi/files/14665704/latest.log)
[2024-03-20-2.log.gz](https://github.com/gdavid04/phi/files/14665705/2024-03-20-2.log.gz)
[2024-03-20-3.log.gz](https://github.com/gdavid04/phi/files/14665707/2024-03-20-3.log.gz)
[2024-03-20-4.log.gz](https://github.com/gdavid04/phi/files/14665708/2024-03-20-4.log.gz)
