### ISSUE TITLE
Phi 1.16-1.6 requires Psi 1.16-95

### ISSUE THREAD

**Issue by justastranger** [gdavid04/phi#5]
The latest release of Psi is 1.16-94, which is the version the Curseforge description says is required.

**Comment by gdavid04** [comment]
Psi 1.16-95 was released at the time Phi 1.16-1.6 was released but it was later pulled from CurseForge. For now, 1.16-1.6 is changed to beta status and requires a beta version of Psi. This will be fixed when Psi 1.16-95 is available on CurseForge again.

**Comment by gdavid04** [comment]
Psi 1.16-95 is available again and I've removed that part from the description.
